### ISSUE TITLE
Add 'migrate' task to support migration to the specmesh way

### ISSUE THREAD

**Issue by bluemonk3y** [specmesh/specmesh-build#170]
Automation tasks should be used to help existing installations migrate to SpecMesh. 

This could look like:
1. User write simple-app with proposed domain id 'somedomain-id' 
- channel names are completed using the proposed naming. i.e. _public.somedata
- channels are annotated with migrate-source tags. 

i.e. 
```
<snip>
  _protected.retail.subway.food.purchase:
    bindings:
      kafka:
    publish:
      tags: [
        name: "migrate-source: existing-topic.blah-stuff.withmessy-name"
      ]
<snip>
```

2. User applies `extract` command to the spec and an existing cluster (should be production)
`simple-template.app` is enriched with the topic config, and schema. Schema file is downloaded to the `/schema` folder.
```
<snip>
  _protected.retail.subway.food.purchase:
    bindings:
      kafka:
        partitions: 10
        configs:
          cleanup.policy: delete
          retention.ms: 9900000
    publish:
      tags: [
        name: "migrate-source: existing-topic.blah-stuff.withmessy-name"
      ]
        payload:
          $ref: "/schema/simple.schema_demo._public.user_info.proto"
<snip>
```

3. User applies `migrate` task. This task will
- create a topic (if it doesn't exist) and configure it with associated settings
- copy topic offsets from the old to new topic
- copy topic data from the old topic to the new topic 

4. Client apps should be pointed to the new topic. They should also use the new domain-id/credentaisls so that ACLs are enforced
