### ISSUE TITLE
Add support for schemas on the Message.key

### ISSUE THREAD

**Issue by bluemonk3y** [specmesh/specmesh-build#301]
**Is your feature request related to a problem? Please describe.**
Currently specmesh supports message->payload->schema - but is missing key schemas - it support 'string' only

Note - With kafka - 'type' information is 'optional' - its a serde/producer/consumer config that determines how the type is captured/implemented. therefore the 'schema' is an optional association on the spec - unless a consumer/producer is parsing the spec to determine which type of serde to use  - i.e. StringSerializer etc

**Describe the solution you'd like**
Need to support key schemas - they might default to a 'string' or primitive type where a schema is not specified

**Describe alternatives you've considered**
do nothing or use strings - but wont work for composite keys

**Additional context**

**Comment by navery-max** [comment]
```
message:
  schemaFormat: "application/vnd.apache.avro+json;version=1.9.0"
  payload:
    type: "record"
    name: "KeyValueMessage"
    fields:
      - name: "key"
        type:
          $ref: "MessageKey.avsc"  # Reference the key schema
      - name: "value"
        type:
          $ref: "MessageValue.avsc"  # Reference the value schema
```


```
message:
  schemaFormat: "application/vnd.apache.avro+json;version=1.9.0"  # Avro for value schema
  payload:
    type: record  # Not strictly required for JSON Schema, but improves readability
    properties:
      key: string  # Inline string type definition for the key
      value:
        type:
          # Reference a separate Avro schema for the value structure
          $ref: "MessageValue.avsc"
```


```

message:
  schemaFormat: application/json
  payload:
    type: record  # Not strictly required for JSON Schema, but improves readability
    properties:
      key:  # Inline long type definition for the key (limited support)
        type: integer  # Avro uses long for integers, but some tools might not handle inline types well
      value:
        type: string  # Avro uses long for integers, but some tools might not handle inline types well
```

**Comment by big-andy-coates** [comment]
I'd go with :

```yaml
message:
  payload:
    properties:
      key: 
         type: 
            long  # in build kafka-type
      value:
        type:
          $ref: "MessageValue.avsc". # avro-type
```

If you want to support `schemaFormat` it should be at the `key` & `value` level, not the `message` level, as you can have a JSON key and Avro value, etc.
